/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksGenerateInvoicesRouteImport } from './routes/hooks/generate-invoices'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ApiTrackRouteImport } from './routes/api/track'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppUsageRouteImport } from './routes/_app/usage'
import { Route as AppSubscriptionRouteImport } from './routes/_app/subscription'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppKeysRouteImport } from './routes/_app/keys'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppApisRouteImport } from './routes/_app/apis'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as ApiWebhooksRazorpayRouteImport } from './routes/api/webhooks/razorpay'
import { Route as ApiSubscriptionCancelRouteImport } from './routes/api/subscription/cancel'
import { Route as ApiPaymentsVerifyRouteImport } from './routes/api/payments/verify'
import { Route as ApiPaymentsListRouteImport } from './routes/api/payments/list'
import { Route as ApiPaymentsCreateOrderRouteImport } from './routes/api/payments/create-order'
import { Route as ApiKeysValidateRouteImport } from './routes/api/keys/validate'
import { Route as ApiKeysListRouteImport } from './routes/api/keys/list'
import { Route as ApiKeysCreateRouteImport } from './routes/api/keys/create'
import { Route as ApiKeysIdRouteImport } from './routes/api/keys/$id'
import { Route as ApiBillingPlansRouteImport } from './routes/api/billing/plans'
import { Route as ApiBillingInvoicesRouteImport } from './routes/api/billing/invoices'
import { Route as ApiBillingGenerateNowRouteImport } from './routes/api/billing/generate-now'
import { Route as ApiBillingCalculateRouteImport } from './routes/api/billing/calculate'
import { Route as ApiAuthConfirmRouteImport } from './routes/api/auth/confirm'
import { Route as ApiApisListRouteImport } from './routes/api/apis/list'
import { Route as ApiApisCreateRouteImport } from './routes/api/apis/create'
import { Route as ApiKeysStatusIdRouteImport } from './routes/api/keys/status.$id'
import { Route as ApiKeysRevokeIdRouteImport } from './routes/api/keys/revoke.$id'
import { Route as ApiKeysRegenerateIdRouteImport } from './routes/api/keys/regenerate.$id'
import { Route as ApiKeysRateLimitIdRouteImport } from './routes/api/keys/rate-limit.$id'
import { Route as ApiGatewayApiIdSplatRouteImport } from './routes/api/gateway.$apiId.$'
import { Route as ApiBillingInvoicePdfIdRouteImport } from './routes/api/billing/invoice-pdf.$id'
import { Route as ApiAuthConfirmIdRouteImport } from './routes/api/auth.confirm.$id'
import { Route as ApiApisUpdateIdRouteImport } from './routes/api/apis/update.$id'
import { Route as ApiApisDetailsIdRouteImport } from './routes/api/apis/details.$id'
import { Route as ApiApisDeleteIdRouteImport } from './routes/api/apis/delete.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksGenerateInvoicesRoute = HooksGenerateInvoicesRouteImport.update({
  id: '/hooks/generate-invoices',
  path: '/hooks/generate-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackRoute = ApiTrackRouteImport.update({
  id: '/api/track',
  path: '/api/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppApisRoute = AppApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiWebhooksRazorpayRoute = ApiWebhooksRazorpayRouteImport.update({
  id: '/api/webhooks/razorpay',
  path: '/api/webhooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionCancelRoute = ApiSubscriptionCancelRouteImport.update({
  id: '/api/subscription/cancel',
  path: '/api/subscription/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsVerifyRoute = ApiPaymentsVerifyRouteImport.update({
  id: '/api/payments/verify',
  path: '/api/payments/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsListRoute = ApiPaymentsListRouteImport.update({
  id: '/api/payments/list',
  path: '/api/payments/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsCreateOrderRoute = ApiPaymentsCreateOrderRouteImport.update({
  id: '/api/payments/create-order',
  path: '/api/payments/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysValidateRoute = ApiKeysValidateRouteImport.update({
  id: '/api/keys/validate',
  path: '/api/keys/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysListRoute = ApiKeysListRouteImport.update({
  id: '/api/keys/list',
  path: '/api/keys/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysCreateRoute = ApiKeysCreateRouteImport.update({
  id: '/api/keys/create',
  path: '/api/keys/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysIdRoute = ApiKeysIdRouteImport.update({
  id: '/api/keys/$id',
  path: '/api/keys/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPlansRoute = ApiBillingPlansRouteImport.update({
  id: '/api/billing/plans',
  path: '/api/billing/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingInvoicesRoute = ApiBillingInvoicesRouteImport.update({
  id: '/api/billing/invoices',
  path: '/api/billing/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingGenerateNowRoute = ApiBillingGenerateNowRouteImport.update({
  id: '/api/billing/generate-now',
  path: '/api/billing/generate-now',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCalculateRoute = ApiBillingCalculateRouteImport.update({
  id: '/api/billing/calculate',
  path: '/api/billing/calculate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthConfirmRoute = ApiAuthConfirmRouteImport.update({
  id: '/api/auth/confirm',
  path: '/api/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApisListRoute = ApiApisListRouteImport.update({
  id: '/api/apis/list',
  path: '/api/apis/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApisCreateRoute = ApiApisCreateRouteImport.update({
  id: '/api/apis/create',
  path: '/api/apis/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysStatusIdRoute = ApiKeysStatusIdRouteImport.update({
  id: '/api/keys/status/$id',
  path: '/api/keys/status/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRevokeIdRoute = ApiKeysRevokeIdRouteImport.update({
  id: '/api/keys/revoke/$id',
  path: '/api/keys/revoke/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRegenerateIdRoute = ApiKeysRegenerateIdRouteImport.update({
  id: '/api/keys/regenerate/$id',
  path: '/api/keys/regenerate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRateLimitIdRoute = ApiKeysRateLimitIdRouteImport.update({
  id: '/api/keys/rate-limit/$id',
  path: '/api/keys/rate-limit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewayApiIdSplatRoute = ApiGatewayApiIdSplatRouteImport.update({
  id: '/api/gateway/$apiId/$',
  path: '/api/gateway/$apiId/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingInvoicePdfIdRoute = ApiBillingInvoicePdfIdRouteImport.update({
  id: '/api/billing/invoice-pdf/$id',
  path: '/api/billing/invoice-pdf/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthConfirmIdRoute = ApiAuthConfirmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAuthConfirmRoute,
} as any)
const ApiApisUpdateIdRoute = ApiApisUpdateIdRouteImport.update({
  id: '/api/apis/update/$id',
  path: '/api/apis/update/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApisDetailsIdRoute = ApiApisDetailsIdRouteImport.update({
  id: '/api/apis/details/$id',
  path: '/api/apis/details/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApisDeleteIdRoute = ApiApisDeleteIdRouteImport.update({
  id: '/api/apis/delete/$id',
  path: '/api/apis/delete/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/apis': typeof AppApisRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/insights': typeof AppInsightsRoute
  '/keys': typeof AppKeysRoute
  '/profile': typeof AppProfileRoute
  '/subscription': typeof AppSubscriptionRoute
  '/usage': typeof AppUsageRoute
  '/api/health': typeof ApiHealthRoute
  '/api/track': typeof ApiTrackRoute
  '/api/version': typeof ApiVersionRoute
  '/hooks/generate-invoices': typeof HooksGenerateInvoicesRoute
  '/api/apis/create': typeof ApiApisCreateRoute
  '/api/apis/list': typeof ApiApisListRoute
  '/api/auth/confirm': typeof ApiAuthConfirmRouteWithChildren
  '/api/billing/calculate': typeof ApiBillingCalculateRoute
  '/api/billing/generate-now': typeof ApiBillingGenerateNowRoute
  '/api/billing/invoices': typeof ApiBillingInvoicesRoute
  '/api/billing/plans': typeof ApiBillingPlansRoute
  '/api/keys/$id': typeof ApiKeysIdRoute
  '/api/keys/create': typeof ApiKeysCreateRoute
  '/api/keys/list': typeof ApiKeysListRoute
  '/api/keys/validate': typeof ApiKeysValidateRoute
  '/api/payments/create-order': typeof ApiPaymentsCreateOrderRoute
  '/api/payments/list': typeof ApiPaymentsListRoute
  '/api/payments/verify': typeof ApiPaymentsVerifyRoute
  '/api/subscription/cancel': typeof ApiSubscriptionCancelRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/api/apis/delete/$id': typeof ApiApisDeleteIdRoute
  '/api/apis/details/$id': typeof ApiApisDetailsIdRoute
  '/api/apis/update/$id': typeof ApiApisUpdateIdRoute
  '/api/auth/confirm/$id': typeof ApiAuthConfirmIdRoute
  '/api/billing/invoice-pdf/$id': typeof ApiBillingInvoicePdfIdRoute
  '/api/gateway/$apiId/$': typeof ApiGatewayApiIdSplatRoute
  '/api/keys/rate-limit/$id': typeof ApiKeysRateLimitIdRoute
  '/api/keys/regenerate/$id': typeof ApiKeysRegenerateIdRoute
  '/api/keys/revoke/$id': typeof ApiKeysRevokeIdRoute
  '/api/keys/status/$id': typeof ApiKeysStatusIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/apis': typeof AppApisRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/insights': typeof AppInsightsRoute
  '/keys': typeof AppKeysRoute
  '/profile': typeof AppProfileRoute
  '/subscription': typeof AppSubscriptionRoute
  '/usage': typeof AppUsageRoute
  '/api/health': typeof ApiHealthRoute
  '/api/track': typeof ApiTrackRoute
  '/api/version': typeof ApiVersionRoute
  '/hooks/generate-invoices': typeof HooksGenerateInvoicesRoute
  '/api/apis/create': typeof ApiApisCreateRoute
  '/api/apis/list': typeof ApiApisListRoute
  '/api/auth/confirm': typeof ApiAuthConfirmRouteWithChildren
  '/api/billing/calculate': typeof ApiBillingCalculateRoute
  '/api/billing/generate-now': typeof ApiBillingGenerateNowRoute
  '/api/billing/invoices': typeof ApiBillingInvoicesRoute
  '/api/billing/plans': typeof ApiBillingPlansRoute
  '/api/keys/$id': typeof ApiKeysIdRoute
  '/api/keys/create': typeof ApiKeysCreateRoute
  '/api/keys/list': typeof ApiKeysListRoute
  '/api/keys/validate': typeof ApiKeysValidateRoute
  '/api/payments/create-order': typeof ApiPaymentsCreateOrderRoute
  '/api/payments/list': typeof ApiPaymentsListRoute
  '/api/payments/verify': typeof ApiPaymentsVerifyRoute
  '/api/subscription/cancel': typeof ApiSubscriptionCancelRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/api/apis/delete/$id': typeof ApiApisDeleteIdRoute
  '/api/apis/details/$id': typeof ApiApisDetailsIdRoute
  '/api/apis/update/$id': typeof ApiApisUpdateIdRoute
  '/api/auth/confirm/$id': typeof ApiAuthConfirmIdRoute
  '/api/billing/invoice-pdf/$id': typeof ApiBillingInvoicePdfIdRoute
  '/api/gateway/$apiId/$': typeof ApiGatewayApiIdSplatRoute
  '/api/keys/rate-limit/$id': typeof ApiKeysRateLimitIdRoute
  '/api/keys/regenerate/$id': typeof ApiKeysRegenerateIdRoute
  '/api/keys/revoke/$id': typeof ApiKeysRevokeIdRoute
  '/api/keys/status/$id': typeof ApiKeysStatusIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/apis': typeof AppApisRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/keys': typeof AppKeysRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/subscription': typeof AppSubscriptionRoute
  '/_app/usage': typeof AppUsageRoute
  '/api/health': typeof ApiHealthRoute
  '/api/track': typeof ApiTrackRoute
  '/api/version': typeof ApiVersionRoute
  '/hooks/generate-invoices': typeof HooksGenerateInvoicesRoute
  '/api/apis/create': typeof ApiApisCreateRoute
  '/api/apis/list': typeof ApiApisListRoute
  '/api/auth/confirm': typeof ApiAuthConfirmRouteWithChildren
  '/api/billing/calculate': typeof ApiBillingCalculateRoute
  '/api/billing/generate-now': typeof ApiBillingGenerateNowRoute
  '/api/billing/invoices': typeof ApiBillingInvoicesRoute
  '/api/billing/plans': typeof ApiBillingPlansRoute
  '/api/keys/$id': typeof ApiKeysIdRoute
  '/api/keys/create': typeof ApiKeysCreateRoute
  '/api/keys/list': typeof ApiKeysListRoute
  '/api/keys/validate': typeof ApiKeysValidateRoute
  '/api/payments/create-order': typeof ApiPaymentsCreateOrderRoute
  '/api/payments/list': typeof ApiPaymentsListRoute
  '/api/payments/verify': typeof ApiPaymentsVerifyRoute
  '/api/subscription/cancel': typeof ApiSubscriptionCancelRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/api/apis/delete/$id': typeof ApiApisDeleteIdRoute
  '/api/apis/details/$id': typeof ApiApisDetailsIdRoute
  '/api/apis/update/$id': typeof ApiApisUpdateIdRoute
  '/api/auth/confirm/$id': typeof ApiAuthConfirmIdRoute
  '/api/billing/invoice-pdf/$id': typeof ApiBillingInvoicePdfIdRoute
  '/api/gateway/$apiId/$': typeof ApiGatewayApiIdSplatRoute
  '/api/keys/rate-limit/$id': typeof ApiKeysRateLimitIdRoute
  '/api/keys/regenerate/$id': typeof ApiKeysRegenerateIdRoute
  '/api/keys/revoke/$id': typeof ApiKeysRevokeIdRoute
  '/api/keys/status/$id': typeof ApiKeysStatusIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/apis'
    | '/billing'
    | '/dashboard'
    | '/insights'
    | '/keys'
    | '/profile'
    | '/subscription'
    | '/usage'
    | '/api/health'
    | '/api/track'
    | '/api/version'
    | '/hooks/generate-invoices'
    | '/api/apis/create'
    | '/api/apis/list'
    | '/api/auth/confirm'
    | '/api/billing/calculate'
    | '/api/billing/generate-now'
    | '/api/billing/invoices'
    | '/api/billing/plans'
    | '/api/keys/$id'
    | '/api/keys/create'
    | '/api/keys/list'
    | '/api/keys/validate'
    | '/api/payments/create-order'
    | '/api/payments/list'
    | '/api/payments/verify'
    | '/api/subscription/cancel'
    | '/api/webhooks/razorpay'
    | '/api/apis/delete/$id'
    | '/api/apis/details/$id'
    | '/api/apis/update/$id'
    | '/api/auth/confirm/$id'
    | '/api/billing/invoice-pdf/$id'
    | '/api/gateway/$apiId/$'
    | '/api/keys/rate-limit/$id'
    | '/api/keys/regenerate/$id'
    | '/api/keys/revoke/$id'
    | '/api/keys/status/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/apis'
    | '/billing'
    | '/dashboard'
    | '/insights'
    | '/keys'
    | '/profile'
    | '/subscription'
    | '/usage'
    | '/api/health'
    | '/api/track'
    | '/api/version'
    | '/hooks/generate-invoices'
    | '/api/apis/create'
    | '/api/apis/list'
    | '/api/auth/confirm'
    | '/api/billing/calculate'
    | '/api/billing/generate-now'
    | '/api/billing/invoices'
    | '/api/billing/plans'
    | '/api/keys/$id'
    | '/api/keys/create'
    | '/api/keys/list'
    | '/api/keys/validate'
    | '/api/payments/create-order'
    | '/api/payments/list'
    | '/api/payments/verify'
    | '/api/subscription/cancel'
    | '/api/webhooks/razorpay'
    | '/api/apis/delete/$id'
    | '/api/apis/details/$id'
    | '/api/apis/update/$id'
    | '/api/auth/confirm/$id'
    | '/api/billing/invoice-pdf/$id'
    | '/api/gateway/$apiId/$'
    | '/api/keys/rate-limit/$id'
    | '/api/keys/regenerate/$id'
    | '/api/keys/revoke/$id'
    | '/api/keys/status/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_app/admin'
    | '/_app/apis'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/insights'
    | '/_app/keys'
    | '/_app/profile'
    | '/_app/subscription'
    | '/_app/usage'
    | '/api/health'
    | '/api/track'
    | '/api/version'
    | '/hooks/generate-invoices'
    | '/api/apis/create'
    | '/api/apis/list'
    | '/api/auth/confirm'
    | '/api/billing/calculate'
    | '/api/billing/generate-now'
    | '/api/billing/invoices'
    | '/api/billing/plans'
    | '/api/keys/$id'
    | '/api/keys/create'
    | '/api/keys/list'
    | '/api/keys/validate'
    | '/api/payments/create-order'
    | '/api/payments/list'
    | '/api/payments/verify'
    | '/api/subscription/cancel'
    | '/api/webhooks/razorpay'
    | '/api/apis/delete/$id'
    | '/api/apis/details/$id'
    | '/api/apis/update/$id'
    | '/api/auth/confirm/$id'
    | '/api/billing/invoice-pdf/$id'
    | '/api/gateway/$apiId/$'
    | '/api/keys/rate-limit/$id'
    | '/api/keys/regenerate/$id'
    | '/api/keys/revoke/$id'
    | '/api/keys/status/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiTrackRoute: typeof ApiTrackRoute
  ApiVersionRoute: typeof ApiVersionRoute
  HooksGenerateInvoicesRoute: typeof HooksGenerateInvoicesRoute
  ApiApisCreateRoute: typeof ApiApisCreateRoute
  ApiApisListRoute: typeof ApiApisListRoute
  ApiAuthConfirmRoute: typeof ApiAuthConfirmRouteWithChildren
  ApiBillingCalculateRoute: typeof ApiBillingCalculateRoute
  ApiBillingGenerateNowRoute: typeof ApiBillingGenerateNowRoute
  ApiBillingInvoicesRoute: typeof ApiBillingInvoicesRoute
  ApiBillingPlansRoute: typeof ApiBillingPlansRoute
  ApiKeysIdRoute: typeof ApiKeysIdRoute
  ApiKeysCreateRoute: typeof ApiKeysCreateRoute
  ApiKeysListRoute: typeof ApiKeysListRoute
  ApiKeysValidateRoute: typeof ApiKeysValidateRoute
  ApiPaymentsCreateOrderRoute: typeof ApiPaymentsCreateOrderRoute
  ApiPaymentsListRoute: typeof ApiPaymentsListRoute
  ApiPaymentsVerifyRoute: typeof ApiPaymentsVerifyRoute
  ApiSubscriptionCancelRoute: typeof ApiSubscriptionCancelRoute
  ApiWebhooksRazorpayRoute: typeof ApiWebhooksRazorpayRoute
  ApiApisDeleteIdRoute: typeof ApiApisDeleteIdRoute
  ApiApisDetailsIdRoute: typeof ApiApisDetailsIdRoute
  ApiApisUpdateIdRoute: typeof ApiApisUpdateIdRoute
  ApiBillingInvoicePdfIdRoute: typeof ApiBillingInvoicePdfIdRoute
  ApiGatewayApiIdSplatRoute: typeof ApiGatewayApiIdSplatRoute
  ApiKeysRateLimitIdRoute: typeof ApiKeysRateLimitIdRoute
  ApiKeysRegenerateIdRoute: typeof ApiKeysRegenerateIdRoute
  ApiKeysRevokeIdRoute: typeof ApiKeysRevokeIdRoute
  ApiKeysStatusIdRoute: typeof ApiKeysStatusIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/generate-invoices': {
      id: '/hooks/generate-invoices'
      path: '/hooks/generate-invoices'
      fullPath: '/hooks/generate-invoices'
      preLoaderRoute: typeof HooksGenerateInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track': {
      id: '/api/track'
      path: '/api/track'
      fullPath: '/api/track'
      preLoaderRoute: typeof ApiTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscription': {
      id: '/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keys': {
      id: '/_app/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apis': {
      id: '/_app/apis'
      path: '/apis'
      fullPath: '/apis'
      preLoaderRoute: typeof AppApisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/webhooks/razorpay': {
      id: '/api/webhooks/razorpay'
      path: '/api/webhooks/razorpay'
      fullPath: '/api/webhooks/razorpay'
      preLoaderRoute: typeof ApiWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscription/cancel': {
      id: '/api/subscription/cancel'
      path: '/api/subscription/cancel'
      fullPath: '/api/subscription/cancel'
      preLoaderRoute: typeof ApiSubscriptionCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/verify': {
      id: '/api/payments/verify'
      path: '/api/payments/verify'
      fullPath: '/api/payments/verify'
      preLoaderRoute: typeof ApiPaymentsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/list': {
      id: '/api/payments/list'
      path: '/api/payments/list'
      fullPath: '/api/payments/list'
      preLoaderRoute: typeof ApiPaymentsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/create-order': {
      id: '/api/payments/create-order'
      path: '/api/payments/create-order'
      fullPath: '/api/payments/create-order'
      preLoaderRoute: typeof ApiPaymentsCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys/validate': {
      id: '/api/keys/validate'
      path: '/api/keys/validate'
      fullPath: '/api/keys/validate'
      preLoaderRoute: typeof ApiKeysValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys/list': {
      id: '/api/keys/list'
      path: '/api/keys/list'
      fullPath: '/api/keys/list'
      preLoaderRoute: typeof ApiKeysListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys/create': {
      id: '/api/keys/create'
      path: '/api/keys/create'
      fullPath: '/api/keys/create'
      preLoaderRoute: typeof ApiKeysCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys/$id': {
      id: '/api/keys/$id'
      path: '/api/keys/$id'
      fullPath: '/api/keys/$id'
      preLoaderRoute: typeof ApiKeysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/plans': {
      id: '/api/billing/plans'
      path: '/api/billing/plans'
      fullPath: '/api/billing/plans'
      preLoaderRoute: typeof ApiBillingPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/invoices': {
      id: '/api/billing/invoices'
      path: '/api/billing/invoices'
      fullPath: '/api/billing/invoices'
      preLoaderRoute: typeof ApiBillingInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/generate-now': {
      id: '/api/billing/generate-now'
      path: '/api/billing/generate-now'
      fullPath: '/api/billing/generate-now'
      preLoaderRoute: typeof ApiBillingGenerateNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/calculate': {
      id: '/api/billing/calculate'
      path: '/api/billing/calculate'
      fullPath: '/api/billing/calculate'
      preLoaderRoute: typeof ApiBillingCalculateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/confirm': {
      id: '/api/auth/confirm'
      path: '/api/auth/confirm'
      fullPath: '/api/auth/confirm'
      preLoaderRoute: typeof ApiAuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apis/list': {
      id: '/api/apis/list'
      path: '/api/apis/list'
      fullPath: '/api/apis/list'
      preLoaderRoute: typeof ApiApisListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apis/create': {
      id: '/api/apis/create'
      path: '/api/apis/create'
      fullPath: '/api/apis/create'
      preLoaderRoute: typeof ApiApisCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys/status/$id': {
      id: '/api/keys/status/$id'
      path: '/api/keys/status/$id'
      fullPath: '/api/keys/status/$id'
      preLoaderRoute: typeof ApiKeysStatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys/revoke/$id': {
      id: '/api/keys/revoke/$id'
      path: '/api/keys/revoke/$id'
      fullPath: '/api/keys/revoke/$id'
      preLoaderRoute: typeof ApiKeysRevokeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys/regenerate/$id': {
      id: '/api/keys/regenerate/$id'
      path: '/api/keys/regenerate/$id'
      fullPath: '/api/keys/regenerate/$id'
      preLoaderRoute: typeof ApiKeysRegenerateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys/rate-limit/$id': {
      id: '/api/keys/rate-limit/$id'
      path: '/api/keys/rate-limit/$id'
      fullPath: '/api/keys/rate-limit/$id'
      preLoaderRoute: typeof ApiKeysRateLimitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gateway/$apiId/$': {
      id: '/api/gateway/$apiId/$'
      path: '/api/gateway/$apiId/$'
      fullPath: '/api/gateway/$apiId/$'
      preLoaderRoute: typeof ApiGatewayApiIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/invoice-pdf/$id': {
      id: '/api/billing/invoice-pdf/$id'
      path: '/api/billing/invoice-pdf/$id'
      fullPath: '/api/billing/invoice-pdf/$id'
      preLoaderRoute: typeof ApiBillingInvoicePdfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/confirm/$id': {
      id: '/api/auth/confirm/$id'
      path: '/$id'
      fullPath: '/api/auth/confirm/$id'
      preLoaderRoute: typeof ApiAuthConfirmIdRouteImport
      parentRoute: typeof ApiAuthConfirmRoute
    }
    '/api/apis/update/$id': {
      id: '/api/apis/update/$id'
      path: '/api/apis/update/$id'
      fullPath: '/api/apis/update/$id'
      preLoaderRoute: typeof ApiApisUpdateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apis/details/$id': {
      id: '/api/apis/details/$id'
      path: '/api/apis/details/$id'
      fullPath: '/api/apis/details/$id'
      preLoaderRoute: typeof ApiApisDetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apis/delete/$id': {
      id: '/api/apis/delete/$id'
      path: '/api/apis/delete/$id'
      fullPath: '/api/apis/delete/$id'
      preLoaderRoute: typeof ApiApisDeleteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppApisRoute: typeof AppApisRoute
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppKeysRoute: typeof AppKeysRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppUsageRoute: typeof AppUsageRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppApisRoute: AppApisRoute,
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppKeysRoute: AppKeysRoute,
  AppProfileRoute: AppProfileRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppUsageRoute: AppUsageRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiAuthConfirmRouteChildren {
  ApiAuthConfirmIdRoute: typeof ApiAuthConfirmIdRoute
}

const ApiAuthConfirmRouteChildren: ApiAuthConfirmRouteChildren = {
  ApiAuthConfirmIdRoute: ApiAuthConfirmIdRoute,
}

const ApiAuthConfirmRouteWithChildren = ApiAuthConfirmRoute._addFileChildren(
  ApiAuthConfirmRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiTrackRoute: ApiTrackRoute,
  ApiVersionRoute: ApiVersionRoute,
  HooksGenerateInvoicesRoute: HooksGenerateInvoicesRoute,
  ApiApisCreateRoute: ApiApisCreateRoute,
  ApiApisListRoute: ApiApisListRoute,
  ApiAuthConfirmRoute: ApiAuthConfirmRouteWithChildren,
  ApiBillingCalculateRoute: ApiBillingCalculateRoute,
  ApiBillingGenerateNowRoute: ApiBillingGenerateNowRoute,
  ApiBillingInvoicesRoute: ApiBillingInvoicesRoute,
  ApiBillingPlansRoute: ApiBillingPlansRoute,
  ApiKeysIdRoute: ApiKeysIdRoute,
  ApiKeysCreateRoute: ApiKeysCreateRoute,
  ApiKeysListRoute: ApiKeysListRoute,
  ApiKeysValidateRoute: ApiKeysValidateRoute,
  ApiPaymentsCreateOrderRoute: ApiPaymentsCreateOrderRoute,
  ApiPaymentsListRoute: ApiPaymentsListRoute,
  ApiPaymentsVerifyRoute: ApiPaymentsVerifyRoute,
  ApiSubscriptionCancelRoute: ApiSubscriptionCancelRoute,
  ApiWebhooksRazorpayRoute: ApiWebhooksRazorpayRoute,
  ApiApisDeleteIdRoute: ApiApisDeleteIdRoute,
  ApiApisDetailsIdRoute: ApiApisDetailsIdRoute,
  ApiApisUpdateIdRoute: ApiApisUpdateIdRoute,
  ApiBillingInvoicePdfIdRoute: ApiBillingInvoicePdfIdRoute,
  ApiGatewayApiIdSplatRoute: ApiGatewayApiIdSplatRoute,
  ApiKeysRateLimitIdRoute: ApiKeysRateLimitIdRoute,
  ApiKeysRegenerateIdRoute: ApiKeysRegenerateIdRoute,
  ApiKeysRevokeIdRoute: ApiKeysRevokeIdRoute,
  ApiKeysStatusIdRoute: ApiKeysStatusIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
